### PR TITLE
Authentication panics when audience field is empty

### PR DESCRIPTION
**Pull request by rafaga**
I have experimented an error trying to authenticate new users into ESI and for some reason the AUDience field its empty, making rfesi to panic without any emaninful message.

I'm adding a validation for such situation

### CODE REVIEW

**Comment by Celeo** [comment]
Hi, thanks for the PR!

Looking at [the docs](https://docs.esi.evetech.net/docs/sso/validating_eve_jwt.html#validate-the-audience-claim), it looks like there'll be 2 items in the "aud" field - is that what you're seeing?

**Comment by Celeo** [comment]
Though [their Python example](https://github.com/esi/esi-docs/blob/master/examples/python/sso/validate_jwt.py#L66) only has the one piece.

**Comment by rafaga** [comment]
It just comes as None so I suppose its empty (I cant debug the crate very well, so I can-t see whats exactly its content)

**Comment by Celeo** [comment]
Ahhh, I see.

**Review by Celeo — APPROVED** [review]

**Comment by Celeo** [comment]
Thank you very much!

**Comment by Celeo** [comment]
Published in [v0.19.0](https://crates.io/crates/rfesi/0.19.0).

**Pull request merged**
