### PR TITLE
JWT Validation - Change from alcoholic_jwt to jsonwebtoken crate 

### PR DESCRIPTION
**Pull request by normegil**
Hello,

I've change the crate for validation due to [alcoholic_jwt](https://github.com/tazjin/alcoholic_jwt) being unmaintened and archived. I've switched to [jsonwebtoken](https://github.com/Keats/jsonwebtoken). I also added some tests for the validation.

Thought you might be interrested.

### CODE REVIEW

**Comment by Celeo** [comment]
Brilliant, thanks!

I'm getting a libc compilation error when trying to use it in a test project. Do you get the same?

```plain
❯ cargo b
    Updating crates.io index
error: failed to select a version for `libc`.
    ... required by package `ring v0.17.4`
    ... which satisfies dependency `ring = "^0.17.4"` of package `jsonwebtoken v9.1.0`
    ... which satisfies dependency `jsonwebtoken = "^9.1.0"` of package `rfesi v0.25.0 (/home/matt/code/rfesi)`
    ... which satisfies path dependency `rfesi` (locked to 0.25.0) of package `rfesi_driver v0.1.0 (/home/matt/code/rfesi_driver)`
versions that meet the requirements `^0.2.148` are: 0.2.150, 0.2.149, 0.2.148

all possible versions conflict with previously selected packages.

  previously selected package `libc v0.2.144`
    ... which satisfies dependency `libc = "^0.2.51"` (locked to 0.2.144) of package `hermit-abi v0.1.19`
    ... which satisfies dependency `hermit-abi = "^0.1.3"` (locked to 0.1.19) of package `num_cpus v1.13.1`
    ... which satisfies dependency `num_cpus = "^1.8.0"` (locked to 1.13.1) of package `tokio v1.21.2`
    ... which satisfies dependency `tokio = "^1.21.2"` (locked to 1.21.2) of package `rfesi_driver v0.1.0 (/home/matt/code/rfesi_driver)`

failed to select a version for `libc` which could resolve this conflict
```

**Comment by normegil** [comment]
I've got no issue, I've just tried to compile rfesi under Windows (cargo 1.75-nightly) & Linux (Ubuntu - cargo 1.72). 

The projet using rfesi works as well.

**Comment by Celeo** [comment]
Gotcha; must've been something on my end.

**Review by Celeo — APPROVED** [review]
Looks great; you even included tests! Thanks much!

**Comment by Celeo** [comment]
Released: https://github.com/Celeo/rfesi/releases/tag/v0.26.0

**Pull request merged**
